"""initial_schema

Revision ID: b600d2e48769
Revises: 
Create Date: 2026-02-23 18:26:52.598942
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = 'b600d2e48769'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('medical_record_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'unknown', name='gender_enum'), nullable=False),
    sa.Column('allergies', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('pre_existing_conditions', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patients_created', 'patients', ['created_at'], unique=False)
    op.create_index(op.f('ix_patients_medical_record_number'), 'patients', ['medical_record_number'], unique=True)
    op.create_index('ix_patients_name', 'patients', ['last_name', 'first_name'], unique=False)
    op.create_table('clinical_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clinical_notes_created', 'clinical_notes', ['created_at'], unique=False)
    op.create_index('ix_clinical_notes_patient', 'clinical_notes', ['patient_id'], unique=False)
    op.create_table('medical_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('modality', sa.Enum('xray', 'ct', 'mri', 'ultrasound', 'other', name='modality_enum'), nullable=False),
    sa.Column('body_region', sa.Enum('chest', 'abdomen', 'head', 'spine', 'extremities', 'pelvis', 'other', name='body_region_enum'), nullable=False),
    sa.Column('analysis_result', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_medical_images_modality', 'medical_images', ['modality'], unique=False)
    op.create_index('ix_medical_images_patient', 'medical_images', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_medical_images_patient', table_name='medical_images')
    op.drop_index('ix_medical_images_modality', table_name='medical_images')
    op.drop_table('medical_images')
    op.drop_index('ix_clinical_notes_patient', table_name='clinical_notes')
    op.drop_index('ix_clinical_notes_created', table_name='clinical_notes')
    op.drop_table('clinical_notes')
    op.drop_index('ix_patients_name', table_name='patients')
    op.drop_index(op.f('ix_patients_medical_record_number'), table_name='patients')
    op.drop_index('ix_patients_created', table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
